[Polyglot] Fail when a string has no description #319
clickcaramel/PolyglotRocks pull request #53
Opened 2023-06-02 12:00 UTC by mr150

2023-06-02 12:01 UTC, mr150 commented on bin/polyglot
> +  echo "  -d, --descr-requirement <OPTION>   How the description will be taken into account for strings (optional)."
Не уверен, что это лучшее название для фичи, но более подходящего не нашел

2023-06-02 12:39 UTC, igooor-bb commented on bin/polyglot
> +elif [ -z "`echo \"${descr_requirement_options[@]}\" | grep $descr_requirement`" ]; then
Не сработает, если передать пустую строку или последовательность пробелов. Нужно проверить и этот вариант

2023-06-02 12:40 UTC, igooor-bb requested changes
См. комментарий

2023-06-03 02:12 UTC, bleshik approved these changes

2023-06-03 09:40 UTC, merged